import serial
import time
import Commands
import Log
import random
#Log.LogMassage("Check Ports","Info","Test","Check","Check")
#SR830 = serial.Serial("COM3", 9600, timeout = 2.0)
#time.sleep (0.5)
#Log.LogMassage("COM4","Info","Test","OpenPort","9600")

#SR830.write(b"*IDN?\r")
#reply = SR830.read_until(b"\r")
#print("Raw: " ,repr(reply))
#print("Decoded: ", reply.decode("ascii", errors="replace").strip())
#time.sleep (1)

#Log.LogMassage(time.strftime("%Y-%m-%d %H:%M:%S"), "Communication", "GetValue", "IDN?", "SR830")
#SR830.write(b"*IDN?\r")
#ValueIDN = SR830.read_until(b"\r")
#ValueIDN = ValueIDN.decode("ascii", errors="replace").strip()
#Log.LogMassage(time.strftime("%Y-%m-%d %H:%M:%S"), "Communication", "GetValue", str(ValueIDN), "SR830")


#Commands.getValue(SR830,"IDN")



#Commands.getValue(SR830,"OUTP1")



#Commands.getValue(SR830,"OUTP1")



#Commands.getValue(SR830,"OUTP1")



#Commands.getValue(SR830,"OUTP1")



Log.Log("Serial Communication", "SR830","S", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FMOD", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "FMOD", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FMOD", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FMOD", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "RSLP", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","F", "FREQ", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","W", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "OsTech","R", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)
Log.Log("Serial Communication", "SR830","E", "PHAS", str(random.randint(0, 100)), "Testing Log and Import", "Wir sind Geil", " Auf jeden", "Fall"," !!!")
time.sleep(random.randint(0, 50)/100)

